import type { TagEntry } from '../types';

/**
 * Seed tags for initializing tag-registry.json.
 * ~80 tags across 5 facet groups: domain, method, algorithm, software, concept.
 * All relations reference only labels that exist within this same array.
 */
export const SEED_TAGS: TagEntry[] = [
  // ================================================================
  // Group 1: Domain (~25 tags)  —  facets: ['domain']
  // ================================================================
  {
    label: 'artificial-intelligence',
    aliases: ['人工智能', 'AI'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [
        'machine-learning',
        'natural-language-processing',
        'computer-vision',
        'knowledge-representation',
        'robotics',
      ],
      related: ['data-science', 'computational-linguistics'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'machine-learning',
    aliases: ['机器学习', 'ML'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['artificial-intelligence'],
      narrower: ['deep-learning'],
      related: ['data-science', 'algorithms-and-complexity'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'deep-learning',
    aliases: ['深度学习', 'DL'],
    facets: ['domain', 'method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['machine-learning'],
      narrower: [],
      related: [
        'neural-network',
        'neural-network-architecture',
        'convolutional-neural-network',
        'recurrent-neural-network',
      ],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'natural-language-processing',
    aliases: ['自然语言处理', 'NLP'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['artificial-intelligence'],
      narrower: [],
      related: ['computational-linguistics', 'information-retrieval'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'computer-vision',
    aliases: ['计算机视觉', 'CV'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['artificial-intelligence'],
      narrower: [],
      related: ['computer-graphics', 'convolutional-neural-network'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'information-retrieval',
    aliases: ['信息检索', 'IR'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['natural-language-processing', 'database-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'knowledge-representation',
    aliases: ['知识表示', 'KR'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['artificial-intelligence'],
      narrower: [],
      related: ['computational-linguistics', 'formal-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'robotics',
    aliases: ['机器人学'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['artificial-intelligence'],
      narrower: [],
      related: ['reinforcement-learning', 'computer-vision'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'software-engineering',
    aliases: ['软件工程', 'SE'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['programming-languages', 'distributed-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'programming-languages',
    aliases: ['编程语言理论', 'PL'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: ['compilers'],
      related: ['software-engineering', 'formal-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'compilers',
    aliases: ['编译器'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['programming-languages'],
      narrower: [],
      related: ['formal-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'formal-methods',
    aliases: ['形式化方法'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['programming-languages', 'theory-of-computation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'computer-networks',
    aliases: ['计算机网络'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['distributed-systems', 'computer-security'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'distributed-systems',
    aliases: ['分布式系统'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['computer-networks', 'cloud-computing', 'operating-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'operating-systems',
    aliases: ['操作系统', 'OS'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['distributed-systems', 'computer-security'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'database-systems',
    aliases: ['数据库系统', 'DBMS'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['information-retrieval', 'cloud-computing'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'cloud-computing',
    aliases: ['云计算'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['distributed-systems', 'database-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'computer-security',
    aliases: ['计算机安全'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: ['cryptography'],
      related: ['computer-networks', 'operating-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'cryptography',
    aliases: ['密码学'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['computer-security'],
      narrower: [],
      related: ['theory-of-computation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'human-computer-interaction',
    aliases: ['人机交互', 'HCI'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['computer-graphics', 'software-engineering'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'computer-graphics',
    aliases: ['计算机图形学', 'CG'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['computer-vision', 'human-computer-interaction'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'data-science',
    aliases: ['数据科学'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['machine-learning', 'artificial-intelligence'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'computational-linguistics',
    aliases: ['计算语言学'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['natural-language-processing', 'knowledge-representation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'theory-of-computation',
    aliases: ['计算理论'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['algorithms-and-complexity', 'formal-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'algorithms-and-complexity',
    aliases: ['算法与复杂性'],
    facets: ['domain'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['theory-of-computation', 'machine-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },

  // ================================================================
  // Group 2: Method (~25 tags)  —  facets: ['method']
  // ================================================================
  {
    label: 'supervised-learning',
    aliases: ['监督学习'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['unsupervised-learning', 'semi-supervised-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'unsupervised-learning',
    aliases: ['无监督学习'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['supervised-learning', 'clustering', 'self-supervised-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'reinforcement-learning',
    aliases: ['强化学习', 'RL'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['supervised-learning', 'robotics'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'semi-supervised-learning',
    aliases: ['半监督学习'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['supervised-learning', 'unsupervised-learning', 'self-supervised-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'transfer-learning',
    aliases: ['迁移学习'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['self-supervised-learning', 'federated-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'self-supervised-learning',
    aliases: ['自监督学习', 'SSL'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['unsupervised-learning', 'semi-supervised-learning', 'transfer-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'federated-learning',
    aliases: ['联邦学习', 'FL'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['transfer-learning', 'distributed-systems'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'transformer',
    aliases: ['Transformer模型', '变换器'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['attention-mechanism', 'self-attention'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'convolutional-neural-network',
    aliases: ['卷积神经网络', 'CNN'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['computer-vision', 'deep-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'recurrent-neural-network',
    aliases: ['循环神经网络', 'RNN'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['deep-learning', 'natural-language-processing'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'generative-adversarial-network',
    aliases: ['生成对抗网络', 'GAN'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['variational-autoencoder', 'deep-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'variational-autoencoder',
    aliases: ['变分自编码器', 'VAE'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['generative-adversarial-network', 'bayesian-inference'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'graph-neural-network',
    aliases: ['图神经网络', 'GNN'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['neural-network-architecture'],
      narrower: [],
      related: ['deep-learning', 'knowledge-representation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'attention-mechanism',
    aliases: ['注意力机制'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: ['self-attention'],
      related: ['transformer'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'self-attention',
    aliases: ['自注意力'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: ['attention-mechanism'],
      narrower: [],
      related: ['transformer'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'gradient-descent',
    aliases: ['梯度下降', 'GD'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['backpropagation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'backpropagation',
    aliases: ['反向传播', 'BP'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['gradient-descent', 'neural-network'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'dropout',
    aliases: ['随机失活'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['regularization', 'batch-normalization'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'batch-normalization',
    aliases: ['批归一化', 'BatchNorm', 'BN'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['dropout', 'neural-network-architecture'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'bayesian-inference',
    aliases: ['贝叶斯推断'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['monte-carlo-methods', 'variational-autoencoder'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'monte-carlo-methods',
    aliases: ['蒙特卡洛方法', 'MCMC'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['bayesian-inference'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'dimensionality-reduction',
    aliases: ['降维'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['principal-component-analysis', 'clustering'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'clustering',
    aliases: ['聚类'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['unsupervised-learning', 'k-means', 'dimensionality-reduction'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'ensemble-methods',
    aliases: ['集成方法', '集成学习'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['random-forest', 'decision-tree'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'neural-network-architecture',
    aliases: ['神经网络架构'],
    facets: ['method'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [
        'transformer',
        'convolutional-neural-network',
        'recurrent-neural-network',
        'generative-adversarial-network',
        'variational-autoencoder',
        'graph-neural-network',
      ],
      related: ['deep-learning', 'neural-network'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },

  // ================================================================
  // Group 3: Algorithm (~10 tags)  —  facets: ['algorithm']
  // ================================================================
  {
    label: 'k-means',
    aliases: ['K均值', 'K-Means'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['clustering', 'unsupervised-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'random-forest',
    aliases: ['随机森林', 'RF'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['decision-tree', 'ensemble-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'support-vector-machine',
    aliases: ['支持向量机', 'SVM'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['supervised-learning', 'logistic-regression'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'k-nearest-neighbors',
    aliases: ['K近邻', 'KNN'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['supervised-learning', 'clustering'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'decision-tree',
    aliases: ['决策树'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['random-forest', 'ensemble-methods'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'logistic-regression',
    aliases: ['逻辑回归'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['linear-regression', 'support-vector-machine'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'linear-regression',
    aliases: ['线性回归'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['logistic-regression'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'principal-component-analysis',
    aliases: ['主成分分析', 'PCA'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['dimensionality-reduction', 'unsupervised-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'bert',
    aliases: ['BERT', '双向编码器表示'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['transformer', 'natural-language-processing', 'gpt'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'gpt',
    aliases: ['GPT', '生成式预训练变换器'],
    facets: ['algorithm'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['transformer', 'natural-language-processing', 'bert'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },

  // ================================================================
  // Group 4: Software (~10 tags)  —  facets: ['software']
  // ================================================================
  {
    label: 'pytorch',
    aliases: ['PyTorch'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['tensorflow', 'deep-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'tensorflow',
    aliases: ['TensorFlow', 'TF'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['pytorch', 'deep-learning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'scikit-learn',
    aliases: ['sklearn', 'Scikit-Learn'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['machine-learning', 'numpy', 'pandas'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'numpy',
    aliases: ['NumPy'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['pandas', 'scikit-learn'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'pandas',
    aliases: ['Pandas'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['numpy', 'scikit-learn', 'data-science'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'jupyter',
    aliases: ['Jupyter Notebook', 'JupyterLab'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['data-science', 'numpy', 'pandas'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'docker',
    aliases: ['Docker', '容器化平台'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['cloud-computing', 'linux'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'git',
    aliases: ['Git', '版本控制系统'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['software-engineering'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'linux',
    aliases: ['Linux', 'GNU/Linux'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['operating-systems', 'docker'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'vscode',
    aliases: ['Visual Studio Code', 'VS Code'],
    facets: ['software'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['software-engineering', 'git'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },

  // ================================================================
  // Group 5: Concept (~10 tags)  —  facets: ['concept']
  // ================================================================
  {
    label: 'overfitting',
    aliases: ['过拟合'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['underfitting', 'bias-variance-tradeoff', 'regularization'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'underfitting',
    aliases: ['欠拟合'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['overfitting', 'bias-variance-tradeoff'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'bias-variance-tradeoff',
    aliases: ['偏差-方差权衡'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['overfitting', 'underfitting', 'cross-validation'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'cross-validation',
    aliases: ['交叉验证', 'CV (交叉验证)'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['bias-variance-tradeoff', 'hyperparameter-tuning'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'regularization',
    aliases: ['正则化'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['overfitting', 'dropout'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'feature-engineering',
    aliases: ['特征工程'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['data-augmentation', 'dimensionality-reduction'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'data-augmentation',
    aliases: ['数据增强'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['feature-engineering', 'overfitting'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'hyperparameter-tuning',
    aliases: ['超参数调优'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['cross-validation', 'model-interpretability'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'model-interpretability',
    aliases: ['模型可解释性', '可解释AI', 'XAI'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: ['hyperparameter-tuning', 'neural-network'],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
  {
    label: 'neural-network',
    aliases: ['神经网络', 'NN'],
    facets: ['concept'],
    status: 'verified',
    flagged: false,
    relations: {
      broader: [],
      narrower: [],
      related: [
        'deep-learning',
        'neural-network-architecture',
        'backpropagation',
        'model-interpretability',
      ],
    },
    source: { verified_by: 'seed', verified_at: '' },
  },
];
