import type { Schema } from '../types';

/** 默认 schema 定义 — 12 种笔记类型 + 40+ facet 定义 */
export const DEFAULT_SCHEMA: Schema = {
  version: 1,
  note_types: {
    academic: {
      label: '学术研究',
      description: '学术论文精读、文献综述、研究方法论笔记、学术概念梳理',
      required_facets: ['domain', 'genre', 'lang'],
      optional_facets: [
        'method', 'algorithm', 'concept', 'dataset',
        'problem', 'software', 'programming-language',
        'scholar', 'venue',
      ],
    },
    project: {
      label: '项目/复现',
      description: '编程项目、论文复现、开源贡献、工程实践记录',
      required_facets: ['domain', 'status', 'tech-stack'],
      optional_facets: [
        'programming-language', 'software',
        'collaborator', 'source-repo',
      ],
    },
    course: {
      label: '课程学习',
      description: '在线课程笔记、教材阅读笔记、课堂记录、学习进度追踪',
      required_facets: ['domain', 'source', 'instructor'],
      optional_facets: ['concept', 'method', 'platform'],
    },
    journal: {
      label: '日记',
      description: '每日日记、情绪记录、生活流水账、个人反思',
      required_facets: ['mood'],
      optional_facets: ['people', 'location', 'event-type', 'reflection-topic'],
    },
    growth: {
      label: '自我成长',
      description: '个人成长反思、习惯养成、心态转变、人生感悟',
      required_facets: ['growth-area'],
      optional_facets: ['method', 'trigger', 'insight-type'],
    },
    relationship: {
      label: '人际关系',
      description: '人物档案、社交关系维护、人际互动记录',
      required_facets: ['person', 'relation-type'],
      optional_facets: ['affiliation', 'domain', 'interaction-type'],
    },
    meeting: {
      label: '会议/社交',
      description: '会议纪要、研讨会笔记、社交活动记录、演讲摘要',
      required_facets: ['participants', 'meeting-type'],
      optional_facets: ['related-project', 'location'],
    },
    finance: {
      label: '财务',
      description: '收支记录、投资分析、预算规划、财务决策',
      required_facets: ['finance-type', 'amount-range'],
      optional_facets: ['category', 'recurring'],
    },
    health: {
      label: '健康',
      description: '健康指标追踪、就医记录、运动日志、饮食与睡眠',
      required_facets: ['health-area'],
      optional_facets: ['metric', 'provider', 'condition'],
    },
    career: {
      label: '职业发展',
      description: '求职记录、技能提升计划、职业转型思考、里程碑',
      required_facets: ['career-aspect'],
      optional_facets: ['company', 'role', 'skill', 'milestone'],
    },
    creative: {
      label: '创作',
      description: '写作草稿、绘画记录、音乐创作、摄影项目、设计灵感',
      required_facets: ['medium', 'status'],
      optional_facets: ['theme', 'audience', 'inspiration'],
    },
    admin: {
      label: '行政/生活',
      description: '日常事务、预约提醒、购物清单、出行规划、证件办理',
      required_facets: ['admin-type'],
      optional_facets: ['deadline', 'priority'],
    },
  },
  facet_definitions: {
    // ── taxonomy 类型 ──
    method: {
      description: '方法论/技术方法',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    algorithm: {
      description: '具体算法',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    concept: {
      description: '核心概念/术语',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    dataset: {
      description: '数据集',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    problem: {
      description: '研究问题/任务',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    domain: {
      description: '所属知识/研究领域',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    'tech-stack': {
      description: '技术栈',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    software: {
      description: '软件工具',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    skill: {
      description: '技能',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    condition: {
      description: '健康状况/疾病',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    'reflection-topic': {
      description: '反思主题',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },
    theme: {
      description: '创作主题',
      value_type: 'taxonomy',
      allow_multiple: true,
      verification_required: true,
    },

    // ── enum 类型 ──
    genre: {
      description: '内容体裁',
      value_type: 'enum',
      values: ['paper', 'textbook', 'tutorial', 'lecture-note', 'blog', 'documentation', 'thesis'],
      blacklist: { article: 'paper', book: 'textbook', guide: 'tutorial', doc: 'documentation' },
      allow_multiple: false,
      verification_required: false,
    },
    lang: {
      description: '语言',
      value_type: 'enum',
      values: ['en', 'zh', 'ja', 'de', 'fr', 'ko'],
      blacklist: { english: 'en', chinese: 'zh', japanese: 'ja', german: 'de', french: 'fr', korean: 'ko' },
      allow_multiple: false,
      verification_required: false,
    },
    mood: {
      description: '情绪状态',
      value_type: 'enum',
      values: ['great', 'good', 'neutral', 'low', 'bad'],
      allow_multiple: false,
      verification_required: false,
    },
    status: {
      description: '进度状态',
      value_type: 'enum',
      values: ['not-started', 'in-progress', 'completed', 'paused', 'abandoned'],
      allow_multiple: false,
      verification_required: false,
    },
    'programming-language': {
      description: '编程语言',
      value_type: 'enum',
      values: ['python', 'javascript', 'typescript', 'java', 'c', 'cpp', 'rust', 'go', 'r', 'julia', 'matlab', 'scala', 'kotlin', 'swift', 'shell'],
      allow_multiple: true,
      verification_required: false,
    },
    'event-type': {
      description: '事件类型',
      value_type: 'enum',
      values: ['social', 'academic', 'family', 'travel', 'work', 'personal'],
      allow_multiple: false,
      verification_required: false,
    },
    'meeting-type': {
      description: '会议类型',
      value_type: 'enum',
      values: ['one-on-one', 'group', 'seminar', 'conference', 'workshop', 'casual'],
      allow_multiple: false,
      verification_required: false,
    },
    'relation-type': {
      description: '人际关系类型',
      value_type: 'enum',
      values: ['friend', 'colleague', 'mentor', 'mentee', 'family', 'acquaintance'],
      allow_multiple: false,
      verification_required: false,
    },
    'interaction-type': {
      description: '互动方式',
      value_type: 'enum',
      values: ['meeting', 'email', 'call', 'chat', 'collaboration'],
      allow_multiple: false,
      verification_required: false,
    },
    'finance-type': {
      description: '财务类型',
      value_type: 'enum',
      values: ['income', 'expense', 'investment', 'debt', 'saving'],
      allow_multiple: false,
      verification_required: false,
    },
    'amount-range': {
      description: '金额区间',
      value_type: 'enum',
      values: ['<100', '100-500', '500-2000', '2000-10000', '>10000'],
      allow_multiple: false,
      verification_required: false,
    },
    category: {
      description: '消费/财务分类',
      value_type: 'enum',
      values: ['food', 'transport', 'housing', 'entertainment', 'education', 'health', 'clothing', 'electronics', 'subscription', 'other'],
      allow_multiple: false,
      verification_required: false,
    },
    recurring: {
      description: '是否周期性',
      value_type: 'enum',
      values: ['daily', 'weekly', 'monthly', 'yearly', 'one-time'],
      allow_multiple: false,
      verification_required: false,
    },
    'health-area': {
      description: '健康领域',
      value_type: 'enum',
      values: ['physical', 'mental', 'sleep', 'nutrition', 'exercise', 'medical'],
      allow_multiple: false,
      verification_required: false,
    },
    'growth-area': {
      description: '成长领域',
      value_type: 'enum',
      values: ['emotional', 'intellectual', 'spiritual', 'social', 'professional', 'physical'],
      allow_multiple: true,
      verification_required: false,
    },
    'career-aspect': {
      description: '职业发展方面',
      value_type: 'enum',
      values: ['job-search', 'skill-development', 'networking', 'promotion', 'transition', 'side-project'],
      allow_multiple: false,
      verification_required: false,
    },
    medium: {
      description: '创作媒介',
      value_type: 'enum',
      values: ['writing', 'drawing', 'music', 'photography', 'video', 'code', 'design'],
      allow_multiple: true,
      verification_required: false,
    },
    'insight-type': {
      description: '洞察类型',
      value_type: 'enum',
      values: ['realization', 'habit-change', 'mindset-shift', 'lesson-learned'],
      allow_multiple: false,
      verification_required: false,
    },
    'admin-type': {
      description: '行政事务类型',
      value_type: 'enum',
      values: ['errand', 'appointment', 'maintenance', 'paperwork', 'shopping', 'travel-planning'],
      allow_multiple: false,
      verification_required: false,
    },
    priority: {
      description: '优先级',
      value_type: 'enum',
      values: ['high', 'medium', 'low'],
      allow_multiple: false,
      verification_required: false,
    },
    platform: {
      description: '学习平台',
      value_type: 'enum',
      values: ['coursera', 'edx', 'youtube', 'udemy', 'mit-ocw', 'stanford-online', 'bilibili', 'other'],
      allow_multiple: false,
      verification_required: false,
    },

    // ── wikilink 类型 ──
    scholar: {
      description: '学者/研究者',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    people: {
      description: '相关人物',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    person: {
      description: '核心人物（关系笔记主体）',
      value_type: 'wikilink',
      allow_multiple: false,
      verification_required: false,
    },
    participants: {
      description: '参与者',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    collaborator: {
      description: '协作者',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    instructor: {
      description: '讲师/教授',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    provider: {
      description: '医疗/服务提供者',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    company: {
      description: '公司/组织',
      value_type: 'wikilink',
      allow_multiple: true,
      verification_required: false,
    },
    'related-project': {
      description: '所属/关联项目',
      value_type: 'wikilink',
      allow_multiple: false,
      verification_required: false,
    },

    // ── free-text 类型 ──
    venue: {
      description: '会议/期刊名称（含年份，如 NeurIPS-2017）',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    source: {
      description: '来源（URL/书名/课程名）',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    'source-repo': {
      description: '源代码仓库 URL',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    location: {
      description: '地点',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    trigger: {
      description: '触发因素',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    inspiration: {
      description: '灵感来源',
      value_type: 'free-text',
      allow_multiple: true,
      verification_required: false,
    },
    audience: {
      description: '目标受众',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    affiliation: {
      description: '所属机构',
      value_type: 'free-text',
      allow_multiple: true,
      verification_required: false,
    },
    metric: {
      description: '健康指标',
      value_type: 'free-text',
      allow_multiple: true,
      verification_required: false,
    },
    role: {
      description: '职位/角色',
      value_type: 'free-text',
      allow_multiple: false,
      verification_required: false,
    },
    milestone: {
      description: '里程碑',
      value_type: 'free-text',
      allow_multiple: true,
      verification_required: false,
    },

    // ── date 类型 ──
    deadline: {
      description: '截止日期（ISO 格式，如 2026-04-15）',
      value_type: 'date',
      allow_multiple: false,
      verification_required: false,
    },
  },
};
